language: ruby
rvm:
  - 2.3.3

install: gem install bundler jekyll

script:
    - bundle update
    - bundle exec jekyll build

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
